apiVersion: v1
kind: Service
metadata:
  name: svc-front
  #서비스이름이 중요.
  #나중에 ingress에서 이걸보고 찾아감.
spec:
  selector:
    app: front
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      name: front-pod
      labels:
        app: front
    spec:
      containers:
      - name: front-con
        image: allogdallog/front:11
