apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      name: front-pod
      labels:
        app: front
    spec:
      containers:
      - name: front-con
        image: allogdallog/front:9
