apiVersion: v1
kind: Service
metadata:
  name: svc-back
  #서비스이름이 중요.
  #나중에 ingress에서 이걸보고 찾아감.
spec:
  selector:
    app: back
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      name: back-pod
      labels:
        app: back
    spec:
      containers:
      - name: back-con
        image: allogdallog/back:11
